spring:
  application:
    name: intelligence-service
  config:
    import: configserver:http://localhost:8888

#  ai:
#    openai:
#      api-key: ${OPENROUTER_API_KEY:${OPENAI_API_KEY:}}
#      base-url: https://openrouter.ai/api
#      chat:
#        options:
#          model: openrouter/free
#          temperature: 0.0
